### ISSUE TITLE
Events are triggered in all models at once

### ISSUE THREAD

**Issue by SparK-Cruz** [raphaelpereira/Backbone.RailsStore#7]
When I save a model, all the listener methods, even on other models are triggered. Also the other models are saved, even tough I called save in only one of them.

**Comment by raphaelpereira** [comment]
This was made on purpose because the complexity involving associations and their persistence. 

Imagine that you have an existing object A in database that is associated with object B, also in database. Then for some reason in the frontend you create object C and associates it with A, replacing B. 
1. If you don't guarantee that upon persistence of A (calling A.save()) C is created, you would have a problem.
2. If you do save C and don't save A, then you also have a problem. Because you would end up with C existing in database, but A doesn't have that situation.

The problem goes beyond even if you don't create new objects, because you need some kind of "atomic" association operation upon save. The most efficient and fast solution I found was to send all changed models to backend on a single "atomic" operation and treat all needed persistence together, avoiding the complex operation.

Obviously we can keep track of the correct associations or create a frontend <-> backend transaction mechanism, but that was too much for my first release.

Said that, I wouldn't treat this as a bug, but rather as a feature request.

:)
